name: Run BlueSky Weather Bot

on:
  schedule:
    - cron: "0 8 * * *"  
  workflow_dispatch: 

jobs:
  run-weather-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Create virtual environment and Install dependencies
        run: |
          chmod +x setup.sh
          ./setup.sh
          
      - name: Create .env file
        run: |
          echo "BLUESKY_HANDLE=${{ secrets.BLUESKY_HANDLE }}" > .env
          echo "BLUESKY_APP_PASSWORD=${{ secrets.BLUESKY_APP_PASSWORD }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          
      - name: Run the script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source .virtualenv/bin/activate
          python main.py
