name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create virtual environment and Install dependencies
      run: |
        chmod +x setup.sh
        ./setup.sh
    - name: Analysing the code with pylint
      run: |
        source .virtualenv/bin/activate
        pylint $(git ls-files '*.py')
